name: co_tuong_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Hỗ trợ đa ngôn ngữ
  flutter_localizations:
    sdk: flutter

  # Thư viện FFI để gọi hàm C++
  ffi: ^2.1.0 

  # --- QUAN TRỌNG: LIÊN KẾT PLUGIN ENGINE LOCAL ---
  # Dòng này bắt buộc phải có để nạp code C++ từ thư mục packages
  pikafish_engine:
    path: ./packages/pikafish_engine
  # ------------------------------------------------

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  path_provider: ^2.1.1
  window_manager: ^0.3.9
  audioplayers: ^6.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Thư viện tạo icon tự động
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/pieces/
    # Lưu ý: pikafish.exe chỉ dùng cho Android/Windows. 
    # iOS sẽ dùng code C++ qua plugin pikafish_engine ở trên.
    - assets/engine/pikafish.exe 
    - assets/engine/pikafish.nnue
    - assets/sounds/
    - assets/icon.png

# Cấu hình tạo icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21